mysite/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    #url(r'^$',views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'\
        r'(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),
     url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list,
        name='post_list_by_tag'),

]

mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',
        include('blog.urls',namespace='blog',app_name='blog')),

]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager
from django.http import cookie

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOISES=(
        ('draft','Roboczy'),
        ('published','Opublikowany'),
    )
    title=models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,unique_for_date='publish')
    author=models.ForeignKey(User,
                             related_name='blog_posts')
    body=models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status=models.CharField(max_length=10,choices=STATUS_CHOISES,default='draft')
    objects=models.Manager()
    published=PublishedManager()
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])



    class Meta:
        ordering=('-publish',)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Komentarz dodany przez {} dla posta {}'.format(self.name, self.post)

mysite/blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

mysite/blog/views.py
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from .models import Post,Comment
from django.views.generic import ListView
from .forms import CommentForm
from taggit.models import Tag

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name ='posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

def post_list(request, tag_slug=None):
        object_list = Post.published.all()
        tag=None
        if tag_slug:
            tag = get_object_or_404(Tag, slug=tag_slug)
            object_list = object_list.filter(tags__in=[tag])
        paginator = Paginator(object_list, 3)
        page = request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            # Jeżeli zmienna page nie jest liczbą całkowitą,
            # wówczas pobierana jest pierwsza strona wyników.
            posts = paginator.page(1)
        except EmptyPage:
            # Jeżeli zmienna page ma wartość większą niż numer ostatniej strony
            # wyników, wtedy pobierana jest ostatnia strona wyników.
            posts = paginator.page(paginator.num_pages)
        return render(request,
                      'blog/post/list.html',
                      {'page': page,
                       'posts': posts,
                       'tag':tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)

    # Lista aktywnych komentarzy dla danego posta.
    comments = post.comments.filter(active=True)

    if request.method == 'POST':
        # Komentarz został opublikowany.
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Utworzenie obiektu Comment, ale jeszcze nie zapisujemy go w bazie danych.
            new_comment = comment_form.save(commit=False)
            # Przypisanie komentarza do bieżącego posta.
            new_comment.post = post
            # Zapisanie komentarza w bazie danych.
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'comment_form': comment_form})

mysite/blog/templates/blog/base.html
{% load blog_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
    <div id="sidebar">
        <h1>Moj blog.</h1><br>
        <p>To jest moj blog. Dotychczas opublikowałem {% total_posts %} postów.</p>
{% show_latest_posts 3 %}
        <h3>Najczęściej komentowane posty</h3>
    {% get_most_commented_posts as most_commented_posts %}
    <ul>
    {% for post in most_commented_posts %}
      <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </li>
    {% endfor %}
    </ul>
    </div>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>

</body>
</html>

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Opublikowany {{ post.publish }} przez {{ post.author }}
  </p>
  {{ post.body|markdown }}
{% with comments.count as total_comments %}
    <h2>
      {{ total_comments }} komentarz{{ total_comments|pluralize:"y" }}
    </h2>
  {% endwith %}
 {% for comment in comments %}
    <div class="comment">
      <p class="info">
        Komentarz {{ forloop.counter }} dodany przez {{ comment.name }}
          {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
  {% empty %}
    <p>Nie ma jeszcze żadnych komentarzy.</p>
  {% endfor %}

  {% if new_comment %}
    <h2>Twój komentarz został dodany.</h2>
  {% else %}
    <h2>Dodaj nowy komentarz</h2>
    <form action="." method="post">
      {{ comment_form.as_p }}
      {% csrf_token %}
      <p><input type="submit" value="Dodaj komentarz"></p>
    </form>
  {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/latest_post.html
<ul>
  {% for post in latest_posts %}
  <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </li>
  {% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}Mój blog{% endblock %}

{% block content %}
  <h1>Mój blog</h1>
  {% if tag %}
    <h2>Posty oznaczone tagiem "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
  <p class="tags">
      Tagi:
      {% for tag in post.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
          {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
      {% endfor %}
</p>
    </p>
    <p class="date">
      Opublikowany {{ post.publish }} przez {{ post.author }}
    </p>
    {{ post.body|markdown|truncatewords_html:30 }}
  {% endfor %}
  {% include "pagination.html" with page=posts%}
{% endblock %}

mysite/blog/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Poprzednia</a>
    {% endif %}
    <span class="current">
      Strona {{ page.number }} z {{ page.paginator.num_pages }}.
    </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Następna</a>
      {% endif %}
  </span>
</div>